### PR TITLE
Update the used MediaWiki rule set to 15.0.0

### PR DESCRIPTION
**Pull request by thiemowmde**
The update from 13 to 14 did not do anything to the effective rule set here (the sniffs updated in 14 are disabled here). That's why I skip it and jump straight to 15.

There is basically only one addition. The ForbiddenFunctions sniff currently disallows these functions: `create_function`, `extract`, and `is_integer`. None is used in our code bases, so this addition should be fine.

### CODE REVIEW

**Review by lucaswerkmeister — COMMENTED** [review]
> The update from 13 to 14 did not do anything

I’m not sure I see that. Did we already have sniffs to “Unwrap types in function docs from {}”?

Apart from this, there are several other changes in this commit – README.md, `@license` change – which I would prefer to have separated (could still be a single GitHub pull request).

**Comment by thiemowmde** [comment]
Yes, the MediaWiki.Commenting.FunctionComment sniff got relevant changes. But it is entirely disabled here because I found it waaaaay to painful. We can revalidate it later (in a separate patch) to see if all the improvements the sniff got since it was created solved enough of the issues.

Splitting this patch is easy. I would just split off entire files. Would this really help reviewing this easier?

**Comment by lucaswerkmeister** [comment]
Thanks for the `FunctionComment` explanation, I missed that part.

I care more about having a nice commit history – in this case, the other changes don’t really hurt while reviewing, once I got over the initial surprise of seeing unexpected changes.

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by thiemowmde** [comment]
I submitted the license tag changes as a separate commit f372ff216d17e5131a659ce5f06d73582860a2dd.

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by lucaswerkmeister** [comment]
Thanks!

**Pull request merged**
